<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5711ab36-229e-4235-98aa-1734d07eef0d</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/section[1]/div[1]/div[2]/ti-button[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-fullWidth-only-on-phone\\ ti-button-has-icon\\ ti-button-secondary\\ hydrated"] &gt; span</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:text=\\"Add new\\"i"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>