<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>236a9780-a211-41b1-bcec-c243ffa8af99</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nach architektur durchsuchen</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-responsiveHeader-nav-panel-hybrid-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Nach Architektur durchsuchen')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Nach Architektur durchsuchen"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Nach Architektur durchsuchen</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>