<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e87c1562-e3e9-46dd-b5d7-776931e2d9ac</elementGuidId>
    <imagePath></imagePath>
    <name>atomic_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/atomic-search-interface[1]/atomic-search-layout[1]/atomic-layout-section[2]/atomic-layout-section[1]/atomic-breadbox[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hydrated"] &gt; [class="hydrated"]:nth-child(1) &gt; [class="hydrated"]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>atomic-breadbox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>