<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3c9380e5-9840-4ed5-a9da-230d46d6b487</elementGuidId>
    <imagePath></imagePath>
    <name>atomic_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/atomic-search-interface[1]/atomic-search-layout[1]/atomic-layout-section[2]/atomic-layout-section[2]/div[1]/div[1]/div[1]/atomic-result-list[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#c7 div &gt; [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>atomic-result-list</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>