<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ec21186-f757-496e-bfdf-8945a5fa3d16</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/atomic-search-interface[1]/atomic-search-layout[1]/atomic-layout-section[2]/atomic-layout-section[1]/div[1]/div[1]/ti-gpn-snapshot[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="search-query-snapshots"] &gt; [class="hydrated"]:nth-child(3)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-gpn-snapshot</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>