<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>91f75be5-06c8-4d70-a69c-e455b9398ed3</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_12</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/div[1]/div[1]/ti-form-element[2]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-bottom-4 ti-form-element ti-form-element-is-required hydrated"]:nth-child(4) &gt; [class="u-fullWidth hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-form-element &gt;&gt; internal:has-text="Doing business as (DBA)"i &gt;&gt; ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>