<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8522a8ae-8889-4d9d-8ed6-cfdf76882028</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_13</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/div[1]/div[1]/ti-form-element[5]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-fullWidth u-margin-bottom-2 hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-form-element &gt;&gt; internal:has-text="* Headquarters corporate tax"i &gt;&gt; ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>