<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>889807c2-889d-4b5a-9869-52695eb45574</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/div[1]/div[1]/ti-tisloc-edit-financial-factors[1]/ti-form-element[6]/div[1]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#totalLiabilities [class="ti_p-input mod-fullWidth hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#totalLiabilities ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>