<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>55e768fd-26dd-47b8-80e8-67c140081a01</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/div[1]/div[1]/ti-tisloc-edit-financial-factors[1]/ti-form-element[1]/ti-select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-bottom-4 ti-form-element hydrated"]:nth-child(2) &gt; [class="u-fullWidth hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-select &gt;&gt; internal:has-text="ARSAUDBRLCADCHFCNYCZKDKKEGPEURGBPHKDHUFIDRILSINRJPYKRWMOPMXNMYRNOKNZDPHPPLNRONRU"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>