<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0040380b-df99-4cd0-b5f4-53addb9d994b</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_16</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[1]/div[2]/ti-tisloc-edit-company-details[1]/div[3]/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sc-ti-tisloc-edit-company-details ti-button-secondary hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Next"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>