<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4cdb534-dbaf-468e-8ea0-aa3fbe7cadf5</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_19</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-tisloc-dialog-launcher[1]/ti-dialog[1]/ti-tisloc-edit-company-details-form[1]/ti-form-element[1]/ti-select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sc-ti-tisloc-edit-company-details-form ti-form-element ti-form-element-is-required hydrated"]:nth-child(1) &gt; [class="editable-company-details-form-element ti-editable-company-details-fullWidth sc-ti-tisloc-edit-company-details-form hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-select &gt;&gt; internal:has-text="SelectAlbaniaAlgeriaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrai"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>