<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>54b2d759-87c6-416c-8014-ff7d92320423</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_14</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/div[1]/div[1]/ti-form-element[7]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-bottom-4 ti-form-element ti-form-element-is-required hydrated"]:nth-child(9) &gt; [class="u-fullWidth hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-form-element &gt;&gt; internal:has-text="Year company was established"i &gt;&gt; ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>