<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>45f2e029-4086-4215-a2f3-049fc5f5ff2d</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_22</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[1]/div[2]/ti-tisloc-edit-company-details[1]/ti-form-element[2]/ti-select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-editable-company-details-fullWidth sc-ti-tisloc-edit-company-details hydrated"]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-select</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>