<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>96896d33-d2c7-43f5-adcb-43a07065ebea</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_20</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-tisloc-dialog-launcher[1]/ti-dialog[1]/ti-tisloc-edit-company-details-form[1]/ti-form-element[2]/ti-input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sc-ti-tisloc-edit-company-details-form ti-form-element ti-form-element-is-required hydrated"]:nth-child(2) &gt; [class="editable-company-details-form-element ti-editable-company-details-fullWidth sc-ti-tisloc-edit-company-details-form hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-form-element &gt;&gt; internal:has-text="Company URL"i &gt;&gt; ti-input</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>