<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d64cd56d-aebb-49f9-818d-56727b444f08</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_18</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/div[1]/div[2]/ti-tisloc-save-warn-modal[1]/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sc-ti-tisloc-save-warn-modal ti-button-text hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Save as draft"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>