<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>233333d7-8cbe-4a31-bfac-ab95eb47035f</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/ti-tisloc-apply-loc-application-wrapper[1]/div[1]/ti-stepper[1]/ti-step[2]/div[2]/ti-tisloc-edit-financial-details[1]/div[1]/ti-form-element[1]/ti-radio-group[1]/ti-radio[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="radio"]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=radio[name="No"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>