<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>57d89f60-a263-4355-9192-dd3e029ba9e8</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_15</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-tisloc-dialog-launcher[1]/ti-dialog[1]/div[1]/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-right-4 ti-button-primary hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Add address"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>