<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b984cd60-acd3-4d13-8ffa-f84e8fc4d8f5</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/ti-checkout-profile-add-edit-cop[1]/div[3]/div[1]/ti-checkout-profile-stepper-wrapper[1]/ti-checkout-profile-stepper[1]/ti-checkout-profile-step[6]/div[2]/ti-checkout-profile-payment[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hydrated\\ ti-checkout-profile-step-active"] [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-checkout-profile-payment</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>