<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>823a60d8-446c-45b7-95ce-1cb77f32df5a</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/ti-checkout-profile-add-edit-cop[1]/div[3]/div[1]/ti-checkout-profile-stepper-wrapper[1]/ti-checkout-profile-stepper[1]/ti-checkout-profile-step[4]/div[2]/ti-checkout-profile-regulation[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hydrated\\ ti-checkout-profile-step-active"] [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["ti-checkout-profile-regulation"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>