<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba846d14-d8b8-421d-94df-98434fa639cf</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/ti-checkout-profile-add-edit-cop[1]/div[3]/div[1]/ti-checkout-profile-stepper-wrapper[1]/ti-checkout-profile-stepper[1]/ti-checkout-profile-step[5]/div[2]/ti-checkout-profile-shipping-methods[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>