<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f7e25ec0-b871-45a0-bb74-5713b3d3bddc</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[3]/section[1]/div[1]/div[1]/div[1]/div[3]/table[1]/tbody[1]/tr[6]/td[3]/ti-button[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#product-622 [class="u-flex"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#product-622 &gt;&gt; internal:text="edit Edit"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>