<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af6586e1-6de4-4f82-85f8-3dd1678e2168</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ti-button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#category_622 [class="ti_myti-api-card-action ti-button-compact ti-button-primary hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#category_622 &gt;&gt; internal:text="Enable"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>