<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>296f5a41-1e8b-4cb0-918e-a514ebf1289d</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/ti-dialog[1]/ti-button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-button-secondary hydrated"]:nth-child(4)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#dialog-api-access &gt;&gt; internal:text="Cancel"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>