<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f446d6f4-e965-4f22-8cc8-9c0fcfe1a819</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/form[2]/div[2]/div[1]/div[1]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="reason1"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Manufacturing is"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>