<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff9156a8-ceca-42fd-9ad5-828f101b2d54</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_myti_dashboard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ti-breadcrumb[1]/ti-breadcrumb-section[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'myTI dashboard')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>myTI dashboard</value>
        <webElementGuid>834f226e-168b-4c3d-bb55-4b7d7559cad7</webElementGuid>
    </webElementProperties>
</WebElementEntity>