<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1af015eb-4c95-40e6-a2f3-708fa516b8ed</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/div[2]/div[2]/ti-header-llc-sidesheet[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-responsiveHeader-top-llc"] &gt; [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-header-llc-sidesheet</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>