<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c094a8e5-0cfb-4ed1-8f7f-033b1b2e3684</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/section[1]/div[1]/div[2]/ti-button[1]/ti-svg-icon[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-fullWidth-only-on-phone\\ u-margin-bottom-8-only-on-phone\\ ti-button-has-icon\\ ti-button-secondary\\ hydrated"] &gt; [class="ti-svg-icon-tertiary\\ ti-svg-icon-size-s\\ hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="plus"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>