<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ed1f4add-8a2f-4dc5-895b-23af11ed7412</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_order now</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[1]/div[4]/div[2]/div[1]/ti-button[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-top-4 ti-button-primary hydrated"] &gt; [class=""]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Order now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Order now"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Order now</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>