<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99124b67-869a-424c-9a47-ae61c70b9441</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[6]/div[2]/ti-order-now-mobile[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>section:nth-child(6) [class="hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-order-now-mobile</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>