<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f4446490-f5a8-4983-b713-1e5e5cd05bd8</elementGuidId>
    <imagePath></imagePath>
    <name>ti_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ti-folder-dialog-launcher[1]/ti-dialog[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti-add-to-cart-dialog ti-dialog hydrated ti-dialog-visible"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Carrier optionsYou can choose"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>