<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>11e53b58-c49c-4f35-95c7-580ec16ad5ed</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_go to summary</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="modalLink"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Go to summary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Go to summary"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Go to summary</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>