<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a89f7f80-88ac-4063-94ce-74971fc53217</elementGuidId>
    <imagePath></imagePath>
    <name>div_responsiveheader-overlay</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[15]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>*:nth-child(1) &gt; *:nth-child(2) &gt; *:nth-child(1) &gt; *:nth-child(16)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'responsiveHeader-overlay')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>responsiveHeader-overlay</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>