<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>726181c7-1e84-4508-93e5-19a967ac0edb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_quicklink_bom</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#quicklink_bom</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'quicklink_bom') and equals(@text,'Cross-reference searchhhh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Cross-reference searchhhh"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>quicklink_bom</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Cross-reference searchhhh</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>