<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>103f93d4-ad48-4a9d-bc67-a48d86edc3e9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_power management</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[2]/div[1]/div[1]/div[1]/ul[1]/li[11]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-megaMenu-nav-list-item"]:nth-child(11) &gt; [class="ti_p-megaMenu-nav-action js-megaMenu-tab js-megaMenu-level-1 js-hasListeners"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Power management')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Power management"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Power management</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>