<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8fd09300-774b-4d55-a2f0-fad3f73b9b04</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/section[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-layout-space-small\\ u-margin-bottom-2"] &gt; [class="ti_p-row"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["div &gt;&gt; internal:has-text=\\"New address* Required* Region\\"i &gt;&gt; nth=1"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>