<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b971c8a5-d67a-4ca6-80cf-35f21aee7ce3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_myti_dashboard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ti-breadcrumb[1]/ti-breadcrumb-section[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="hydrated"]:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'myTI dashboard')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=main &gt;&gt; internal:role=link[name=\\"myTI dashboard\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>myTI dashboard</value>
        <webElementGuid>c8c7bd0f-6168-4d79-8367-a652e7ac6984</webElementGuid>
    </webElementProperties>
</WebElementEntity>