<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>36ed2498-8fe8-48c5-901e-6a3d67711834</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/form[2]/div[1]/section[2]/div[1]/div[1]/ti-table-controller[1]/div[2]/table[1]/tbody[1]/tr[6]/td[11]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tr:nth-child(6) &gt; td &gt; div &gt; [class="nomodalLink"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="CPR241016322 dash OPA07-"i] &gt;&gt; internal:role=link &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>