<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>64a23717-3227-446e-9fdc-0d8a7a8ef394</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_checkout profiles</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/div[1]/div[1]/div[1]/section[1]/ul[3]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-list-unstyled myti-dashboard-leftnav-section"]:nth-child(3) &gt; li:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Checkout profiles')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Checkout profiles"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Checkout profiles</value>
        <webElementGuid>0684f39b-6849-4ab9-a802-9db88e2afade</webElementGuid>
    </webElementProperties>
</WebElementEntity>