<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c58226cc-1c1e-4c82-881c-782b4104b374</elementGuidId>
    <imagePath></imagePath>
    <name>label_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/form[1]/div[1]/div[13]/div[5]/div[1]/div[1]/label[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="Repeatable1"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#partDetails-1 &gt;&gt; internal:text="Repeatable"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>