<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>15b77872-adc2-44bf-bcc2-3b8e4e465a24</elementGuidId>
    <imagePath></imagePath>
    <name>label_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/form[1]/div[1]/div[13]/div[7]/div[1]/div[1]/label[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="Do not know31"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.row &gt; div:nth-child(7) &gt; .c8 &gt; .toggle-buttons &gt; .right-btnS &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>