<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b106d4f-8db1-423d-bb39-ba857e5d2158</elementGuidId>
    <imagePath></imagePath>
    <name>ti_addToSamplesCart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/ti-add-to-samples-cart[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="u-margin-bottom-3 hydrated"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-add-to-samples-cart</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>